### ISSUE TITLE
ModuleNotFoundError: No module named 'metalcomputebabel'

### ISSUE THREAD

**Issue by loopless** [ProteusMRIgHIFU/BabelViscoFDTD#7]
Max OS X 13.3.1, Macbook Pro 14"
I was able to successfully build everything  and run the notebook, but it failed at step #1 with ModuleNotFoundError: No module named 'metalcomputebabel'

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 6
      4 from BabelViscoFDTD.H5pySimple import ReadFromH5py,SaveToH5py
      5 from BabelViscoFDTD.PropagationModel import PropagationModel
----> 6 from BabelViscoFDTD.tools.RayleighAndBHTE import *
      7 PModel=PropagationModel()

File /opt/homebrew/Caskroom/miniforge/base/envs/Babel/lib/python3.9/site-packages/BabelViscoFDTD/tools/RayleighAndBHTE.py:231
    227 ctx = None
    229 if sys.platform == "darwin":
--> 231     import metalcomputebabel as mc
    233     # Loads METAL interface
    234     os.environ['__BabelMetal'] =os.path.dirname(os.path.abspath(__file__))

ModuleNotFoundError: No module named 'metalcomputebabel'

**Comment by spichardo** [comment]
Hi,
As indicated in the README file, you need to install a library that is not in pip, just install it with
`pip install  git+https://github.com/ProteusMRIgHIFU/py-metal-compute.git`
After that, it should work.

**Comment by loopless** [comment]
Thanks, I missed that one.
